version: "3.9"

services:
  postgres:
    image: postgres
    container_name: flats_db
    environment:
      POSTGRES_USER: mariik
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flats_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: always

  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "8000:8000"
    restart: always

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - server
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

volumes:
  db:
  server:
  client:
